#!/usr/bin/env python
# -*- coding: utf-8 -*-

#import
#from PIL import Image

#Def vars
loop = 1
choice = 0

while loop == 1:
    choice = raw_input("Recipe: ")
    if choice == "5" or choice == "planks":
        print "- - - - - - - - - - - - - - - - - - -"
        print "Planks:"
        print ""
        print "W=Wood"
        print ""
        print "  | | \n  |W| \n  | |"
        print "- - - - - - - - - - - - - - - - - - -"
    elif choice == "23" or choice == "dispenser":
        print "- - - - - - - - - - - - - - - - - - -"
        print "Dispenser:"
        print ""
        print "C=Cobblestone \nB=Bow \nR=Redstone Dust"
        print ""
        print " C|C|C \n C|B|C \n C|R|C"
        print "- - - - - - - - - - - - - - - - - - -"
    elif choice == "25" or choice == "note block":
        print "- - - - - - - - - - - - - - - - - - -"
        print "Note Block:"
        print ""
        print "P=Planks \nR=Redstone Dust"
        print ""
        print " P|P|P \n P|R|P \n P|P|P"
        print "- - - - - - - - - - - - - - - - - - -"
    elif choice == "27" or choice == "powered rail":
        print "- - - - - - - - - - - - - - - - - - -"
        print "Powered Rail:"
        print ""
        print "G=Gold \nS=Stick \nR=Redstone Dust"
        print ""
        print " G| |G \n G|S|G \n G|R|G"
        print "- - - - - - - - - - - - - - - - - - -"
    elif choice == "28" or choice == "detector rail":
        print "- - - - - - - - - - - - - - - - - - -"
        print "Detector Rail:"
        print ""
        print "I=Iron Ingot \nP=Stone Pressure Plate \nR=Redstone Dust"
        print ""
        print " I| |I \n I|P|I \n I|R|I"
        print "- - - - - - - - - - - - - - - - - - -"
    elif choice == "29" or choice == "sticky piston":
        print "- - - - - - - - - - - - - - - - - - -"
        print "Sticky Piston:"
        print ""
        print "P=Piston \nS=Slimeball"
        print ""
        print "  | | \n  |S|  \n  |P| "
        print "- - - - - - - - - - - - - - - - - - -"
    elif choice == "33" or choice == "piston":
        print "- - - - - - - - - - - - - - - - - - -"
        print "Piston:"
        print ""
        print "C=Cobblestone \nP=Planks \nR=Redstone Dust \nI=Iron Ingot"
        print ""
        print " P|P|P \n C|I|C \n C|R|C"
        print "- - - - - - - - - - - - - - - - - - -"

    #wool options
    elif choice == "35" or choice == "wool":
        print "- - - - - - - - - - - - - - - - - - -"
        print "Please define which wool:"
        print ""
        print "white wool=35:0"
        print "orange wool=35:1"
        print "magenta wool=35:2"
        print "light blue wool=35:3"
        print "yellow wool=35:4"
        print "lime wool=35:5"
        print "pink wool=35:6"
        print "grey wool=35:7"
        print "light grey wool=35:8"
        print "cyan wool=35:9"
        print "purple wool=35:10"
        print "blue wool=35:11"
        print "brown wool=35:12"
        print "green wool=35:13"
        print "red wool=35:14"
        print "black wool=35:15"
        print "- - - - - - - - - - - - - - - - - - -"

    elif choice == "35:0" or choice == "white wool":
        print "- - - - - - - - - - - - - - - - - - -"
        print "White Wool:"
        print ""
        print "S=String"
        print ""
        print "  | | \n S|S| \n S|S|"
        print "- - - - - - - - - - - - - - - - - - -"
    elif choice == "35:1" or choice == "orange wool":
        print "- - - - - - - - - - - - - - - - - - -"
        print "Orange Wool:"
        print ""
        print "W=White Wool \nO=Orange Dye"
        print ""
        print "  | | \n  | | \n W| |O"
        print "- - - - - - - - - - - - - - - - - - -"
    elif choice == "35:2" or choice == "magenta wool":
        print "- - - - - - - - - - - - - - - - - - -"
        print "Magenta Wool:"
        print ""
        print "W=White Wool \nM=Magenta Dye"
        print ""
        print "  | | \n  | | \n W| |M"
        print "- - - - - - - - - - - - - - - - - - -"
    elif choice == "35:3" or choice == "light blue wool":
        print "- - - - - - - - - - - - - - - - - - -"
        print "Light Blue Wool:"
        print ""
        print "W=White Wool \nL=Light Blue Dye"
        print ""
        print "  | | \n  | | \n W| |L"
        print "- - - - - - - - - - - - - - - - - - -"
    elif choice == "35:4" or choice == "yellow wool":
        print "- - - - - - - - - - - - - - - - - - -"
        print "Yellow Wool:"
        print ""
        print "W=White Wool \nD=Dandelion Yellow"
        print ""
        print "  | | \n  | | \n W| |D"
        print "- - - - - - - - - - - - - - - - - - -"
    elif choice == "35:5" or choice == "lime wool":
        print "- - - - - - - - - - - - - - - - - - -"
        print "Lime Wool:"
        print ""
        print "W=White Wool \nL=Lime Dye"
        print ""
        print "  | | \n  | | \n W| |L"
        print "- - - - - - - - - - - - - - - - - - -"
    elif choice == "35:6" or choice == "pink wool":
        print "- - - - - - - - - - - - - - - - - - -"
        print "Pink Wool:"
        print ""
        print "W=White Wool \nP=Pink Dye"
        print ""
        print "  | | \n  | | \n W| |O"
        print "- - - - - - - - - - - - - - - - - - -"
    elif choice == "35:7" or choice == "grey wool" or choice == "gray wool":
        print "- - - - - - - - - - - - - - - - - - -"
        print "Grey Wool:"
        print ""
        print "W=White Wool \nG=Gray Dye"
        print ""
        print "  | | \n  | | \n W| |G"
        print "- - - - - - - - - - - - - - - - - - -"
    elif choice == "35:8" or choice == "light grey wool" or choice == "light gray wool":
        print "- - - - - - - - - - - - - - - - - - -"
        print "Light Grey Wool:"
        print ""
        print "W=White Wool \nL=Light Gray Dye"
        print ""
        print "  | | \n  | | \n W| |L"
        print "- - - - - - - - - - - - - - - - - - -"
    elif choice == "35:9" or choice == "cyan wool":
        print "- - - - - - - - - - - - - - - - - - -"
        print "Cyan Wool:"
        print ""
        print "W=White Wool \nC=Cyan Dye"
        print ""
        print "  | | \n  | | \n W| |C"
        print "- - - - - - - - - - - - - - - - - - -"
    elif choice == "35:10" or choice == "purple wool" or choice == "violet wool":
        print "- - - - - - - - - - - - - - - - - - -"
        print "Purple Wool:"
        print ""
        print "W=White Wool \nP=Purple Dye"
        print ""
        print "  | | \n  | | \n W| |P"
        print "- - - - - - - - - - - - - - - - - - -"
    elif choice == "35:11" or choice == "blue wool":
        print "- - - - - - - - - - - - - - - - - - -"
        print "Blue Wool:"
        print ""
        print "W=White Wool \nL=Lapiz Lazuli Dye"
        print ""
        print "  | | \n  | | \n W| |L"
        print "- - - - - - - - - - - - - - - - - - -"
    elif choice == "35:12" or choice == "brown wool":
        print "- - - - - - - - - - - - - - - - - - -"
        print "Brown Wool:"
        print ""
        print "W=White Wool \nC=Cocoa Beans"
        print ""
        print "  | | \n  | | \n W| |C"
        print "- - - - - - - - - - - - - - - - - - -"
    elif choice == "35:13" or choice == "green wool":
        print "- - - - - - - - - - - - - - - - - - -"
        print "Green Wool:"
        print ""
        print "W=White Wool \nC=Cactus Green"
        print ""
        print "  | | \n  | | \n W| |C"
        print "- - - - - - - - - - - - - - - - - - -"
    elif choice == "35:14" or choice == "red wool":
        print "- - - - - - - - - - - - - - - - - - -"
        print "Red Wool:"
        print ""
        print "W=White Wool \nR=Rose Red"
        print ""
        print "  | | \n  | | \n W| |R"
        print "- - - - - - - - - - - - - - - - - - -"
    elif choice == "35:15" or choice == "black wool":
        print "- - - - - - - - - - - - - - - - - - -"
        print "Black Wool:"
        print ""
        print "W=White Wool \nI=Inc Sac"
        print ""
        print "  | | \n  | | \n W| |I"
        print "- - - - - - - - - - - - - - - - - - -"
    elif choice == "41" or choice == "gold block":
        print "- - - - - - - - - - - - - - - - - - -"
        print "Gold Block:"
        print ""
        print "G=Gold Ingot"
        print ""
        print " G|G|G \n G|G|G \n G|G|G"
        print "- - - - - - - - - - - - - - - - - - -"
    elif choice == "42" or choice == "iron block":
        print "- - - - - - - - - - - - - - - - - - -"
        print "Iron Block:"
        print ""
        print "I=Iron Ingot"
        print ""
        print " I|I|I \n I|I|I \n I|I|I"
        print "- - - - - - - - - - - - - - - - - - -"
    elif choice == "41" or choice == "gold block":
        print "- - - - - - - - - - - - - - - - - - -"
        print "Gold Block:"
        print ""
        print "G=Gold Ingot"
        print ""
        print " G|G|G \n G|G|G \n G|G|G"
        print "- - - - - - - - - - - - - - - - - - -"

    #slab options
    elif choice == "44" or choice == "slab":
        print "- - - - - - - - - - - - - - - - - - -"
        print "Please define which slab:"
        print ""
        print "stone slab=44:0"
        print "sandstone slab=44:1"
        print "wooden slab=44:2"
        print "cobblestone slab=44:3"
        print "brick slab=44:4"
        print "stone brick slab=44:5"
        print "- - - - - - - - - - - - - - - - - - -"

    elif choice == "44:0" or choice == "stone slab":
        print "- - - - - - - - - - - - - - - - - - -"
        print "Stone Slab:"
        print ""
        print "S=Stone"
        print ""
        print "  | | \n  | | \n S|S|S"
        print "- - - - - - - - - - - - - - - - - - -"
    elif choice == "44:1" or choice == "sandstone slab":
        print "- - - - - - - - - - - - - - - - - - -"
        print "Sandstone Slab:"
        print ""
        print "S=Sandstone"
        print ""
        print "  | | \n  | | \n S|S|S"
        print "- - - - - - - - - - - - - - - - - - -"
    elif choice == "44:2" or choice == "wooden slab" or choice == "wood slab":
        print "- - - - - - - - - - - - - - - - - - -"
        print "Wooden Slab:"
        print ""
        print "P=Planks"
        print ""
        print "  | | \n  | | \n P|P|P"
        print "- - - - - - - - - - - - - - - - - - -"
    elif choice == "44:3" or choice == "cobblestone slab":
        print "- - - - - - - - - - - - - - - - - - -"
        print "Cobblestone Slab:"
        print ""
        print "C=Cobblestone"
        print ""
        print "  | | \n  | | \n C|C|C"
        print "- - - - - - - - - - - - - - - - - - -"
    elif choice == "44:4" or choice == "brick slab":
        print "- - - - - - - - - - - - - - - - - - -"
        print "Brick Slab:"
        print ""
        print "B=Bricks"
        print ""
        print "  | | \n  | | \n B|B|B"
        print "- - - - - - - - - - - - - - - - - - -"
    elif choice == "44:5" or choice == "stonebrick slab":
        print "- - - - - - - - - - - - - - - - - - -"
        print "Stone brick Slab:"
        print ""
        print "S=Stone brick"
        print ""
        print "  | | \n  | | \n S|S|S"
        print "- - - - - - - - - - - - - - - - - - -"
    elif choice == "45" or choice == "brick block" or choice == "bricks":
        print "- - - - - - - - - - - - - - - - - - -"
        print "Bricks:"
        print ""
        print "C=Clay Bricks"
        print ""
        print "  | | \n C|C| \n C|C|"
        print "- - - - - - - - - - - - - - - - - - -"
    elif choice == "46" or choice == "TNT" or choice == "tnt":
        print "- - - - - - - - - - - - - - - - - - -"
        print "TNT:"
        print ""
        print "G=Gunpowder \nS=Sand"
        print ""
        print " G|S|G \n S|G|S \n G|S|G"
        print "- - - - - - - - - - - - - - - - - - -"
    elif choice == "47" or choice == "bookshelf" or choice == "bookselves":
        print "- - - - - - - - - - - - - - - - - - -"
        print "Bookshelf:"
        print ""
        print "B=Book \nP=Planks"
        print ""
        print " P|P|P \n B|B|B \n P|P|P"
        print "- - - - - - - - - - - - - - - - - - -"
    elif choice == "50" or choice == "torch":
        print "- - - - - - - - - - - - - - - - - - -"
        print "Torch:"
        print ""
        print "S=Stick \nC=Coal or Charcoal"
        print ""
        print "  | | \n  |C| \n  |S|"
        print "- - - - - - - - - - - - - - - - - - -"

    #stairs options
    elif choice == "stair" or choice == "stairs":
        print "- - - - - - - - - - - - - - - - - - -"
        print "Please define which stairs:"
        print ""
        print "wooden stairs=53"
        print "cobblestone stairs=67"
        print "brick stairs=108"
        print "stone brick stairs=109"
        print "netherbrick stairs=114"
        print "- - - - - - - - - - - - - - - - - - -"

    elif choice == "53" or choice == "wood stairs" or choice == "wooden stairs":
        print "- - - - - - - - - - - - - - - - - - -"
        print "Wooden Stairs:"
        print ""
        print "P=Planks"
        print ""
        print " P| | \n P|P| \n P|P|P"
        print "- - - - - - - - - - - - - - - - - - -"
    elif choice == "54" or choice == "chest":
        print "- - - - - - - - - - - - - - - - - - -"
        print "Chest:"
        print ""
        print "P=Planks"
        print ""
        print " P|P|P \n P| |P \n P|P|P"
        print "- - - - - - - - - - - - - - - - - - -"
    elif choice == "57" or choice == "diamond block":
        print "- - - - - - - - - - - - - - - - - - -"
        print "Diamond Block:"
        print ""
        print "D=Diamond"
        print ""
        print " D|D|D \n D|D|D \n D|D|D"
        print "- - - - - - - - - - - - - - - - - - -"
    elif choice == "58" or choice == "crafting table":
        print "- - - - - - - - - - - - - - - - - - -"
        print "Crafting Table:"
        print ""
        print "P=Planks"
        print ""
        print "  | | \n P|P| \n P|P|"
        print "- - - - - - - - - - - - - - - - - - -"
    elif choice == "61" or choice == "furnace":
        print "- - - - - - - - - - - - - - - - - - -"
        print "Furnace:"
        print ""
        print "C=Cobblestone"
        print ""
        print " C|C|C \n C| |C \n C|C|C"
        print "- - - - - - - - - - - - - - - - - - -"
    elif choice == "65" or choice == "ladder":
        print "- - - - - - - - - - - - - - - - - - -"
        print "Ladder:"
        print ""
        print "S=Stick"
        print ""
        print " S| |S \n S|S|S \n S| |S"
        print "- - - - - - - - - - - - - - - - - - -"
    elif choice == "66" or choice == "rail":
        print "- - - - - - - - - - - - - - - - - - -"
        print "rail:"
        print ""
        print "S=Stick \nI=Iron Ingot"
        print ""
        print " I| |I \n I|S|I \n I| |I"
        print "- - - - - - - - - - - - - - - - - - -"
    elif choice == "67" or choice == "cobblestone stair" or choice == "cobblestone stairs":
        print "- - - - - - - - - - - - - - - - - - -"
        print "Cobblestone Stairs:"
        print ""
        print "C=Cobblestone"
        print ""
        print " C| | \n C|C| \n C|C|C"
        print "- - - - - - - - - - - - - - - - - - -"
    elif choice == "69" or choice == "lever":
        print "- - - - - - - - - - - - - - - - - - -"
        print "Lever:"
        print ""
        print "S=Stick \nC=Cobblestone"
        print ""
        print "  | | \n  |S| \n  |C|"
        print "- - - - - - - - - - - - - - - - - - -"
    elif choice == "70" or choice == "stone pressure plate":
        print "- - - - - - - - - - - - - - - - - - -"
        print "Stone Pressure Plate:"
        print ""
        print "S=Stone"
        print ""
        print "  | | \n  | | \n S|S|"
        print "- - - - - - - - - - - - - - - - - - -"
    elif choice == "72" or choice == "wooden pressure plate" or choice == "wood pressure plate":
        print "- - - - - - - - - - - - - - - - - - -"
        print "Wooden Pressure Plate:"
        print ""
        print "P=Planks"
        print ""
        print "  | | \n  | | \n P|P|"
        print "- - - - - - - - - - - - - - - - - - -"
    elif choice == "76" or choice == "redstone torch":
        print "- - - - - - - - - - - - - - - - - - -"
        print "Redstone Torch:"
        print ""
        print "R=Redstone Dust \nS=Stick"
        print ""
        print "  | | \n  |R| \n  |S|"
        print "- - - - - - - - - - - - - - - - - - -"
    elif choice == "77" or choice == "button":
        print "- - - - - - - - - - - - - - - - - - -"
        print "Button:"
        print ""
        print "S=Stone"
        print ""
        print "  | | \n  |S| \n  |S|"
        print "- - - - - - - - - - - - - - - - - - -"
    elif choice == "80" or choice == "snow block":
        print "- - - - - - - - - - - - - - - - - - -"
        print "Snow Block:"
        print ""
        print "S=Snowball"
        print ""
        print "  | | \n S|S| \n S|S|"
        print "- - - - - - - - - - - - - - - - - - -"
    elif choice == "84" or choice == "jukebox":
        print "- - - - - - - - - - - - - - - - - - -"
        print "Jukebox:"
        print ""
        print "P=Planks \nD=Diamond"
        print ""
        print " P|P|P \n P|D|P \n P|P|P"
        print "- - - - - - - - - - - - - - - - - - -"

    #fence options
    elif choice == "fence":
        print "- - - - - - - - - - - - - - - - - - -"
        print "Please define which fence:"
        print ""
        print "wooden fence=85"
        print "netherbrick fence=113"
        print "fence gate=107"
        print "- - - - - - - - - - - - - - - - - - -"

    elif choice == "85" or choice == "wood fence" or choice == "wooden fence":
        print "- - - - - - - - - - - - - - - - - - -"
        print "Wooden Fence:"
        print ""
        print "S=Stick"
        print ""
        print "  | | \n S|S|S \n S|S|S"
        print "- - - - - - - - - - - - - - - - - - -"
    elif choice == "89" or choice == "glowstone" or choice == "glowstone block":
        print "- - - - - - - - - - - - - - - - - - -"
        print "Glowstone:"
        print ""
        print "G=Glowstone Dust"
        print ""
        print "  | | \n G|G| \n G|G|"
        print "- - - - - - - - - - - - - - - - - - -"
    elif choice == "91" or choice == "jack o lantern" or choice == "jack-o-lantern":
        print "- - - - - - - - - - - - - - - - - - -"
        print "Jack-O-Lantern:"
        print ""
        print "T=Torch \nP=Pumpkin"
        print ""
        print "  | | \n  |P| \n  |T|"
        print "- - - - - - - - - - - - - - - - - - -"
    elif choice == "92" or choice == "354" or choice == "cake":
        print "- - - - - - - - - - - - - - - - - - -"
        print "Cake:"
        print ""
        print "S=Sugar \nM=Milk Bucket \nW=Wheat \nE=Egg"
        print ""
        print " M|M|M \n S|E|S \n W|W|W"
        print "- - - - - - - - - - - - - - - - - - -"
    elif choice == "96" or choice == "trapdoor" or choice == "trap door":
        print "- - - - - - - - - - - - - - - - - - -"
        print "Trap Door:"
        print ""
        print "P=Planks"
        print ""
        print "  | | \n P|P|P \n P|P|P"
        print "- - - - - - - - - - - - - - - - - - -"
    elif choice == "98" or choice == "stone brick" or choice == "stone bricks":
        print "- - - - - - - - - - - - - - - - - - -"
        print "Stone Brick:"
        print ""
        print "S=Stone"
        print ""
        print "  | | \n S|S| \n S|S|"
        print "- - - - - - - - - - - - - - - - - - -"
    elif choice == "101" or choice == "iron bars" or choice == "bars":
        print "- - - - - - - - - - - - - - - - - - -"
        print "Iron Bars:"
        print ""
        print "I=Iron Ingots"
        print ""
        print "  | | \n I|I|I \n I|I|I"
        print "- - - - - - - - - - - - - - - - - - -"
    elif choice == "102" or choice == "glass" or choice == "glass pane":
        print "- - - - - - - - - - - - - - - - - - -"
        print "Glass Pane:"
        print ""
        print "G=Glass Block"
        print ""
        print "  | | \n G|G|G \n G|G|G"
        print "- - - - - - - - - - - - - - - - - - -"
    elif choice == "107" or choice == "fence gate" or choice == "gate":
        print "- - - - - - - - - - - - - - - - - - -"
        print "Fence Gate:"
        print ""
        print "S=Sticks \nP=Planks"
        print ""
        print "  | | \n S|P|S \n S|P|S"
        print "- - - - - - - - - - - - - - - - - - -"
    elif choice == "108" or choice == "brick stair" or choice == "brick stairs":
        print "- - - - - - - - - - - - - - - - - - -"
        print "Brick Stairs:"
        print ""
        print "B=Bricks"
        print ""
        print " B| | \n B|B| \n B|B|B"
        print "- - - - - - - - - - - - - - - - - - -"
    elif choice == "109" or choice == "stone brick stair" or choice == "stone brick stairs":
        print "- - - - - - - - - - - - - - - - - - -"
        print "Stone Brick Stairs:"
        print ""
        print "S=Stone brick or Cracked Stone Bricks or Mossy Stone Bricks"
        print ""
        print " S| | \n S|S| \n S|S|S"
        print "- - - - - - - - - - - - - - - - - - -"
    elif choice == "113" or choice == "nether brick fence" or choice == "netherbrick fence":
        print "- - - - - - - - - - - - - - - - - - -"
        print "Nether Brick Fence:"
        print ""
        print "N=Nether brick"
        print ""
        print "  | | \n N|N|N \n N|N|N"
        print "- - - - - - - - - - - - - - - - - - -"
    elif choice == "114" or choice == "nether brick stair" or choice == "nether brick stairs" or choice == "netherbrick stair" or choice == "netherbrick stairs":
        print "- - - - - - - - - - - - - - - - - - -"
        print "Nether Brick Stairs:"
        print ""
        print "N=Nether brick"
        print ""
        print " N| | \n N|N|\n N|N|N"
        print "- - - - - - - - - - - - - - - - - - -"
    elif choice == "116" or choice == "enchantment table" or choice == "enchanting table":
        print "- - - - - - - - - - - - - - - - - - -"
        print "Enchantment Table:"
        print ""
        print "D=Diamond \nO=Obsidian \nB=Book"
        print ""
        print "  |B| \n D|O|D \n O|O|O"
        print "- - - - - - - - - - - - - - - - - - -"
    elif choice == "shovel":
        print "- - - - - - - - - - - - - - - - - - -"
        print "Shovel:"
        print ""
        print "X=Wood or Cobblestone or Iron or Gold or Diamond \nS=Stick"
        print ""
        print "  |X| \n  |S| \n  |S|"
        print "- - - - - - - - - - - - - - - - - - -"
    elif choice == "pickaxe" or choice == "pick" or choice == "pick axe":
        print "- - - - - - - - - - - - - - - - - - -"
        print "Pickaxe:"
        print ""
        print "X=Wood or Cobblestone or Iron or Gold or Diamond \nS=Stick"
        print ""
        print " X|X|X \n  |S| \n  |S|"
        print "- - - - - - - - - - - - - - - - - - -"
    elif choice == "axe":
        print "- - - - - - - - - - - - - - - - - - -"
        print "Axe:"
        print ""
        print "X=Wood or Cobblestone or Iron or Gold or Diamond \nS=Stick"
        print ""
        print "  |X|X \n  |S|X \n  |S|"
        print "- - - - - - - - - - - - - - - - - - -"
    elif choice == "259" or choice == "flint and steel":
        print "- - - - - - - - - - - - - - - - - - -"
        print "Flint and Steel:"
        print ""
        print "I=Iron \nF=Flint"
        print ""
        print "  | | \n I| | \n  |F|"
        print "- - - - - - - - - - - - - - - - - - -"
    elif choice == "261" or choice == "bow":
        print "- - - - - - - - - - - - - - - - - - -"
        print "Bow:"
        print ""
        print "T=String \nS=Stick"
        print ""
        print " T|S| \n T| |S \n T|S|"
        print "- - - - - - - - - - - - - - - - - - -"
    elif choice == "262" or choice == "arrow":
        print "- - - - - - - - - - - - - - - - - - -"
        print "Arrow:"
        print ""
        print "F=Flint \nS=Stick \nR=Feather"
        print ""
        print "  |F| \n  |S| \n  |R|"
        print "- - - - - - - - - - - - - - - - - - -"
    elif choice == "265" or choice == "Iron Ingot":
        print "- - - - - - - - - - - - - - - - - - -"
        print "Iron Ingot:"
        print ""
        print "B=Iron Block"
        print ""
        print "  | | \n  |B| \n  | |"
        print "- - - - - - - - - - - - - - - - - - -"
    elif choice == "266" or choice == "gold ingot":
        print "- - - - - - - - - - - - - - - - - - -"
        print "Gold Ingot:"
        print ""
        print "N=Gold Nugget"
        print ""
        print " N|N|N \n N|N|N \n N|N|N"
        print ""
        print "---OR---"
        print ""
        print "B=Gold Block"
        print "  | | \n  |B| \n  | |"
        print "- - - - - - - - - - - - - - - - - - -"

    elif choice == "sword":
        print "- - - - - - - - - - - - - - - - - - -"
        print "Sword:"
        print ""
        print "X=Wood or Cobblestone or Iron or Gold or Diamond \nS=Stick"
        print ""
        print "  |X| \n  |X| \n  |S|"
        print "- - - - - - - - - - - - - - - - - - -"
    elif choice == "280" or choice == "stick":
        print "- - - - - - - - - - - - - - - - - - -"
        print "Stick:"
        print ""
        print "P=Planks"
        print ""
        print "  | | \n P| | \n P| |"
        print "- - - - - - - - - - - - - - - - - - -"
    elif choice == "281" or choice == "bowl":
        print "- - - - - - - - - - - - - - - - - - -"
        print "Bowl:"
        print ""
        print "P=Planks"
        print ""
        print "  | | \n P| |P \n  |P|"
        print "- - - - - - - - - - - - - - - - - - -"
    elif choice == "282" or choice == "mushroom soup" or choice == "mushroom stew":
        print "- - - - - - - - - - - - - - - - - - -"
        print "Mushroom stew:"
        print ""
        print "R=Red Mushroom \nM=Broun Mushroom \nB=Bowl"
        print ""
        print "  |R| \n  |M| \n  |B|"
        print "- - - - - - - - - - - - - - - - - - -"
    elif choice == "287" or choice == "string":
        print "- - - - - - - - - - - - - - - - - - -"
        print "String:"
        print ""
        print "W=Wool"
        print ""
        print "  | | \n W|W| \n W|W|"
        print "- - - - - - - - - - - - - - - - - - -"
    elif choice == "hoe":
        print "- - - - - - - - - - - - - - - - - - -"
        print "Hoe:"
        print ""
        print "X=Wood or Cobblestone or Iron or Gold or Diamond \nS=Stick"
        print ""
        print "  |X|X \n  |S| \n  |S|"
        print "- - - - - - - - - - - - - - - - - - -"
    elif choice == "297" or choice == "bread":
        print "- - - - - - - - - - - - - - - - - - -"
        print "Bread:"
        print ""
        print "W=Wheat"
        print ""
        print "  | | \n  | | \n W|W|W"
        print "- - - - - - - - - - - - - - - - - - -"

    #armor choices
    elif choice == "armor":
        print "- - - - - - - - - - - - - - - - - - -"
        print "Please define which armor:"
        print ""
        print "helmet"
        print "chestplate"
        print "leggings"
        print "boots"
        print "- - - - - - - - - - - - - - - - - - -"

    elif choice == "helmet":
        print "- - - - - - - - - - - - - - - - - - -"
        print "Helmet:"
        print ""
        print "X=Leather or Iron or Fire or Gold or Diamond"
        print ""
        print " X|X|X \n X| |X \n  | |"
        print "- - - - - - - - - - - - - - - - - - -"
    elif choice == "chestplate":
        print "- - - - - - - - - - - - - - - - - - -"
        print "Chestplate:"
        print ""
        print "X=Leather or Iron or Fire or Gold or Diamond"
        print ""
        print " X| |X \n X|X|X \n X|X|X"
        print "- - - - - - - - - - - - - - - - - - -"
    elif choice == "leggings" or choice == "pants":
        print "- - - - - - - - - - - - - - - - - - -"
        print "Leggings:"
        print ""
        print "X=Leather or Iron or Fire or Gold or Diamond"
        print ""
        print " X|X|X \n X| |X \n X| |X"
        print "- - - - - - - - - - - - - - - - - - -"
    elif choice == "boots" or choice == "shoes":
        print "- - - - - - - - - - - - - - - - - - -"
        print "Shoes:"
        print ""
        print "X=Leather or Iron or Fire or Gold or Diamond"
        print ""
        print "  | | \n X| |X \n X| |X"
        print "- - - - - - - - - - - - - - - - - - -"
    elif choice == "321" or choice == "painting":
        print "- - - - - - - - - - - - - - - - - - -"
        print "Painting:"
        print ""
        print "W=Wool \n S=Stick"
        print ""
        print " S|S|S \n S|W|S \n S|S|S"
        print "- - - - - - - - - - - - - - - - - - -"
    elif choice == "322" or choice == "golden apple" or choice == "gold apple":
        print "- - - - - - - - - - - - - - - - - - -"
        print "Golden Apple:"
        print ""
        print "G=Gold Nugget \nA=Apple"
        print ""
        print " G|G|G \n G|A|G \n G|G|G"
        print "- - - - - - - - - - - - - - - - - - -"
    elif choice == "323" or choice == "sign":
        print "- - - - - - - - - - - - - - - - - - -"
        print "Sign:"
        print ""
        print "S=Stick \nP=Planks"
        print ""
        print " P|P|P \n P|P|P \n  |S|"
        print "- - - - - - - - - - - - - - - - - - -"

    #Door Options
    elif choice == "door":
        print "- - - - - - - - - - - - - - - - - - -"
        print "Please define which door:"
        print ""
        print "wooden door=324"
        print "iron door=330"
        print "- - - - - - - - - - - - - - - - - - -"

    elif choice == "324" or choice == "wooden door" or choice == "wood door":
        print "- - - - - - - - - - - - - - - - - - -"
        print "Wooden Door:"
        print ""
        print "P=Planks"
        print ""
        print " P|P| \n P|P| \n P|P|"
        print "- - - - - - - - - - - - - - - - - - -"
    elif choice == "325" or choice == "bucket":
        print "- - - - - - - - - - - - - - - - - - -"
        print "Bucket:"
        print ""
        print "I=Iron Ingot"
        print ""
        print "  | | \n I| |I \n  |I|"
        print "- - - - - - - - - - - - - - - - - - -"
    elif choice == "328" or choice == "minecart":
        print "- - - - - - - - - - - - - - - - - - -"
        print "Minecart:"
        print ""
        print "I=Iron Ingot "
        print ""
        print "  | | \n I| |I \n I|I|I"
        print "- - - - - - - - - - - - - - - - - - -"
    elif choice == "330" or choice == "iron door":
        print "- - - - - - - - - - - - - - - - - - -"
        print "Iron Door:"
        print ""
        print "I=Iron Ingot"
        print ""
        print " I|I| \n I|I| \n I|I|"
        print "- - - - - - - - - - - - - - - - - - -"
    elif choice == "333" or choice == "boat":
        print "- - - - - - - - - - - - - - - - - - -"
        print "Boat:"
        print ""
        print "P=Planks"
        print ""
        print "  | | \n P| |P \n P|P|P"
        print "- - - - - - - - - - - - - - - - - - -"
    elif choice == "339" or choice == "paper":
        print "- - - - - - - - - - - - - - - - - - -"
        print "Paper:"
        print ""
        print "S=Sugarcane"
        print ""
        print "  | | \n  | | \n S|S|S"
        print "- - - - - - - - - - - - - - - - - - -"
    elif choice == "340" or choice == "book":
        print "- - - - - - - - - - - - - - - - - - -"
        print "Book:"
        print ""
        print "P=Paper"
        print ""
        print "  |P| \n  |P| \n  |P|"
        print "- - - - - - - - - - - - - - - - - - -"
    elif choice == "342" or choice == "minecart with chest" or choice == "minecart chest":
        print "- - - - - - - - - - - - - - - - - - -"
        print "Minecart with Chest:"
        print ""
        print "C=Chest \nM=Minecart"
        print ""
        print "  | | \n  |C| \n  |M|"
        print "- - - - - - - - - - - - - - - - - - -"
    elif choice == "343" or choice == "powered minecart" or choice == "minecart with furnace":
        print "- - - - - - - - - - - - - - - - - - -"
        print "Powered Minecart:"
        print ""
        print "F=Furnace \n M=Minecart"
        print ""
        print "  | | \n  |F| \n  |M|"
        print "- - - - - - - - - - - - - - - - - - -"
    elif choice == "345" or choice == "compass":
        print "- - - - - - - - - - - - - - - - - - -"
        print "Compass:"
        print ""
        print "R=Redstone Dust \nI=Iron Ingot "
        print ""
        print "  |I| \n I|R|I \n  |I|"
        print "- - - - - - - - - - - - - - - - - - -"
    elif choice == "346" or choice == "fishing rod":
        print "- - - - - - - - - - - - - - - - - - -"
        print "Fishing Rod:"
        print ""
        print "S=String \n T=Stick"
        print ""
        print "  | |T \n  |T|S \n T| |S"
        print "- - - - - - - - - - - - - - - - - - -"
    elif choice == "347" or choice == "clock" or choice == "watch":
        print "- - - - - - - - - - - - - - - - - - -"
        print "Clock:"
        print ""
        print "G=Gold Ingot \nR=Redstone"
        print ""
        print "  |G| \n G|R|G \n  |G|"
        print "- - - - - - - - - - - - - - - - - - -"

    #Dye options
    elif choice == "351" or choice == "dye":
        print "- - - - - - - - - - - - - - - - - - -"
        print "Please define which dye:"
        print ""
        print "rose red=351:1"
        print "purple=351:5"
        print "cyan=351:6"
        print "light gray=351:7"
        print "gray=351:8"
        print "pink=351:9"
        print "lime green=351:10"
        print "dandelion yellow=351:11"
        print "light blue=351:12"
        print "magenta=351:13"
        print "orange=351:14"
        print "bone meal=351:15"
        print "- - - - - - - - - - - - - - - - - - -"

    elif choice == "351:1" or choice == "rose red" or choice == "rose red dye":
        print "- - - - - - - - - - - - - - - - - - -"
        print "Rose Red Dye:"
        print ""
        print "R=Rose"
        print ""
        print "  | | \n  |R| \n  | |"
        print "- - - - - - - - - - - - - - - - - - -"
    elif choice == "351:5" or choice == "purple" or choice == "purple dye":
        print "- - - - - - - - - - - - - - - - - - -"
        print "Purple Dye:"
        print ""
        print "R=Rose Red \nL=Lapiz Lazuli"
        print ""
        print "  | | \n L| |R \n  | |"
        print "- - - - - - - - - - - - - - - - - - -"
    elif choice == "351:6" or choice == "cyan" or choice == "cyan dye":
        print "- - - - - - - - - - - - - - - - - - -"
        print "Cyan Dye:"
        print ""
        print "G=Cactus Green \nL=Lapiz Lazuli"
        print ""
        print "  | | \n G| |L \n  | |"
        print "- - - - - - - - - - - - - - - - - - -"
    elif choice == "351:7" or choice == "light gray" or choice == "light grey" or choice == "light gray dye" or choice == "light grey dye":
        print "- - - - - - - - - - - - - - - - - - -"
        print "Light Gray Dye:"
        print ""
        print "I=Inc Sac \nB=Bone Meal \nG=Light Gray Die"
        print ""
        print "  | |        | | \n I|B|B  OR  G| |B\n  | |        | |"
        print "- - - - - - - - - - - - - - - - - - -"
    elif choice == "351:8" or choice == "gray" or choice == "grey" or choice == "gray dye" or choice == "grey dye":
        print "- - - - - - - - - - - - - - - - - - -"
        print "Gray Dye:"
        print ""
        print "B=Bone Meal \nI=Inc Sac"
        print ""
        print "  | | \n B| |I \n  | |"
        print "- - - - - - - - - - - - - - - - - - -"
    elif choice == "351:9" or choice == "pink" or choice == "Pink dye":
        print "- - - - - - - - - - - - - - - - - - -"
        print "Pink Dye:"
        print ""
        print "B=Bone Meal \nR=Rose Red"
        print ""
        print "  | | \n B| |R \n  | |"
        print "- - - - - - - - - - - - - - - - - - -"
    elif choice == "351:10" or choice == "lime green" or choice == "light green" or choice == "lime green dye" or choice == "light green dye":
        print "- - - - - - - - - - - - - - - - - - -"
        print "Lime Green Dye:"
        print ""
        print "G=Cactus Green \nB=Bone Meal"
        print ""
        print "  | | \n G| |B \n  | |"
        print "- - - - - - - - - - - - - - - - - - -"
    elif choice == "351:11" or choice == "dandelion yellow" or choice == "yellow" or choice == "dandelion yellow dye" or choice == "yellow dye":
        print "- - - - - - - - - - - - - - - - - - -"
        print "Dandelion Yellow Dye:"
        print ""
        print "D=Dandelion"
        print ""
        print "  | | \n  |D| \n  | |"
        print "- - - - - - - - - - - - - - - - - - -"
    elif choice == "351:12" or choice == "light blue" or choice == "light blue dye":
        print "- - - - - - - - - - - - - - - - - - -"
        print "Light Blue Dye:"
        print ""
        print "B=Bone Meal \nL=Lapiz Lazuli"
        print ""
        print "  | | \n B| |L \n  | |"
        print "- - - - - - - - - - - - - - - - - - -"
    elif choice == "351:13" or choice == "magenta" or choice == "magenta dye":
        print "- - - - - - - - - - - - - - - - - - -"
        print "Magenta Dye:"
        print ""
        print "P=Purple \nK=Pink \nL=Lapiz Lazuli \nB=Bone Meal \nR=Rose Red"
        print ""
        print "  | |        | |       | | \n P| |K  OR  L|B|  OR  K|R|L \n  | |       R|R|       | |"
        print "- - - - - - - - - - - - - - - - - - -"
    elif choice == "351:14" or choice == "orange" or choice == "orange dye":
        print "- - - - - - - - - - - - - - - - - - -"
        print "Orange Dye:"
        print ""
        print "R=Rose Red \nY=Dandelion Yellow"
        print ""
        print "  | | \n R| |Y \n  | |"
        print "- - - - - - - - - - - - - - - - - - -"
    elif choice == "351:15" or choice == "bone meal" or choice == "white" or choice == "bone meal dye" or choice == "white dye":
        print "- - - - - - - - - - - - - - - - - - -"
        print "Bone Meal:"
        print ""
        print "B=Bone"
        print ""
        print "  | | \n  |B| \n  | |"
        print "- - - - - - - - - - - - - - - - - - -"
    elif choice == "355" or choice == "bed":
        print "- - - - - - - - - - - - - - - - - - -"
        print "Bed:"
        print ""
        print "W=Wool \n P=Planks"
        print ""
        print "  | | \n W|W|W \n P|P|P"
        print "- - - - - - - - - - - - - - - - - - -"
    elif choice == "356" or choice == "repeater" or choice == "redstone repeater":
        print "- - - - - - - - - - - - - - - - - - -"
        print "Redstone Repeater:"
        print ""
        print "T=Redstone Torch \nD=Redstone Dust \nS=Stone"
        print ""
        print "  | | \n T|D|T \n S|S|S"
        print "- - - - - - - - - - - - - - - - - - -"
    elif choice == "357" or choice == "cookie":
        print "- - - - - - - - - - - - - - - - - - -"
        print "Cookie:"
        print ""
        print "W=Wheat \nC=Cocoa Beans"
        print ""
        print "  | | \n  | | \n W|C|W"
        print "- - - - - - - - - - - - - - - - - - -"
    elif choice == "358" or choice == "map":
        print "- - - - - - - - - - - - - - - - - - -"
        print "Map:"
        print ""
        print "P=Paper \nC=Compass"
        print ""
        print " P|P|P \n P|C|P \n P|P|P"
        print "- - - - - - - - - - - - - - - - - - -"
    elif choice == "359" or choice == "shears":
        print "- - - - - - - - - - - - - - - - - - -"
        print "Shears:"
        print ""
        print "I=Iron Ingot"
        print ""
        print "  | | \n I| |I \n  |I|"
        print "- - - - - - - - - - - - - - - - - - -"
    elif choice == "374" or choice == "glass bottle" or choice == "bottle":
        print "- - - - - - - - - - - - - - - - - - -"
        print "Glass Bottle:"
        print ""
        print "G=Glass (Block)"
        print ""
        print "  | | \n G| |G \n  |G|"
        print "- - - - - - - - - - - - - - - - - - -"

    elif choice == "376" or choice == "fermented spider eye":
        print "- - - - - - - - - - - - - - - - - - -"
        print "Fermented Spider Eye:"
        print ""
        print "S=Sugar \nB=Brown Mushroom \nE=Spider Eye"
        print ""
        print "  |B| \n  |S| \n  |E|"
        print "- - - - - - - - - - - - - - - - - - -"
    elif choice == "377" or choice == "blaze powder":
        print "- - - - - - - - - - - - - - - - - - -"
        print "Blaze Powder:"
        print ""
        print "R=Blaze Rod"
        print ""
        print "  | | \n  |R| \n  | |"
        print "- - - - - - - - - - - - - - - - - - -"
    elif choice == "378" or choice == "magma cream" or choice == "magma creme":
        print "- - - - - - - - - - - - - - - - - - -"
        print "Magma Cream:"
        print ""
        print "S=Slime Ball \nB=Blaze Powder"
        print ""
        print "  | | \n  |S| \n  |B|"
        print "- - - - - - - - - - - - - - - - - - -"
    elif choice == "379" or choice == "brewing stand":
        print "- - - - - - - - - - - - - - - - - - -"
        print "Brewing Stand:"
        print ""
        print "B=Blaze Rod \nC=Cobblestone"
        print ""
        print "  | | \n  |B| \n C|C|C"
        print "- - - - - - - - - - - - - - - - - - -"
    elif choice == "380" or choice == "cauldron":
        print "- - - - - - - - - - - - - - - - - - -"
        print "Cauldron:"
        print ""
        print "I=Iron Ingot"
        print ""
        print " I| |I \n I| |I \n I|I|I"
        print "- - - - - - - - - - - - - - - - - - -"
    elif choice == "381" or choice == "eye of ender":
        print "- - - - - - - - - - - - - - - - - - -"
        print "Eye of Ender:"
        print ""
        print "P=Ender Pearl \n B=Blaze Powder"
        print ""
        print "  | | \n  |P| \n |B|"
        print "- - - - - - - - - - - - - - - - - - -"
    elif choice == "382" or choice == "glistering melon" or choice == "glistening melon" or choice == "shining melon" or choice == "glittering melon":
        print "- - - - - - - - - - - - - - - - - - -"
        print "Glistering Melon:"
        print ""
        print "M=Melon \nN=Gold Nugget"
        print ""
        print "  | | \n M|N| \n  | |"
        print "- - - - - - - - - - - - - - - - - - -"

    #FIXME: Needs to launch pix when data entry received
    #opens info images
    """
    elif choice == "data values" or choice == "data value" or choice == "item" or choice == "items" or choice == "objects":
        print ""
        print "Loading image..."
        print ""
        print "loading failed."
        picture = Image.open("DataValues.png")
        #picture.show()
    elif choice == "brewing" or choice == "alchemy":
        print ""
        print "Loading image..."
        print ""
        print "loading failed."
        picture = Image.open("Brewing.png")
        picture.show()
    elif choice == "dye" or choice == "dying" or choice == "color" or choice == "colors" or choice == "coloring":
        print ""
        print "Loading image..."
        print ""
        print "loading failed."
        picture = Image.open("Colors.png")
        picture.show()
    """

    #other options
    if choice == "help" or choice == "?":
        print "- - - - - - - - - - - - - - - - - - -"
        print "Craftbook Help"
        print ""
        print "How to use Craftbook:"
        print "\tTo use Craftbook, simply type in \n\tthe name or ID of an object \n\tfound in Minecraft and press \n\t<enter>. It will then give you \n\tthe name of the object and how \n\tto craft it in a crafting table. \n\tTo quit Craftbook, type 'stop' \n\tor 'quit' into the input area \n\tand press <enter>. Type 'about' \n\tinto the input area and press \n\t<enter> for program information."
        print "- - - - - - - - - - - - - - - - - - -"
    elif choice == "about":
        print "- - - - - - - - - - - - - - - - - - -"
        print "Craftbook V 1.1.0 \n  Built for Minecraft V 1.1.0"
        print ""
        print "Dev Team: \n  Ben Schwabe"
        print ""
        print "e-mail: \n  cc14@teampr0xy.net"
        print "- - - - - - - - - - - - - - - - - - -"
    elif choice == "quit" or choice == "stop" or choice == "close":
        loop = 0
    else:
        print ""
        print "Your input was not recognized. Please try again."
        print ""
